name: Publish Python Package

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache-dependency-path: pyproject.toml

    - name: Install and configure Poetry
      run: |
          python3 -m pip install poetry==1.4.2
          python3 -m poetry config virtualenvs.in-project true
          python3 -m poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: Install dependencies
      run: |
        python3 -m poetry install --without test

    - name: Publish
      run: |
        python3 -m poetry publish --build
